package model;
// Generated Oct 10, 2017 10:03:24 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aluguer generated by hbm2java
 */
@Entity
@Table(name="aluguer"
    ,catalog="cedascasas"
)
public class Aluguer  implements java.io.Serializable {


     private int idaluguer;
     private Cliente cliente;
     private Residencia residencia;
     private Utilizador utilizador;
     private Date data;
     private String prazoContrato;

    public Aluguer() {
    }

	
    public Aluguer(int idaluguer, Cliente cliente, Residencia residencia,Utilizador utilizador) {
        this.idaluguer = idaluguer;
        this.cliente = cliente;
        this.residencia = residencia;
        this.utilizador = utilizador;
    }
    public Aluguer(int idaluguer, Cliente cliente, Residencia residencia,Utilizador utilizador, Date data, String prazoContrato) {
       this.idaluguer = idaluguer;
       this.cliente = cliente;
       this.residencia = residencia;
       this.utilizador = utilizador;
       this.data = data;
       this.prazoContrato = prazoContrato;
    }
   
     @Id 

    
    @Column(name="idaluguer", unique=true, nullable=false)
    public int getIdaluguer() {
        return this.idaluguer;
    }
    
    public void setIdaluguer(int idaluguer) {
        this.idaluguer = idaluguer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Residencia_idResidencia", nullable=false)
    public Residencia getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(Residencia residencia) {
        this.residencia = residencia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="utilizador_idutilizador", nullable=false)
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador (Utilizador utilizador) {
        this.utilizador = utilizador;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="prazoContrato", length=45)
    public String getPrazoContrato() {
        return this.prazoContrato;
    }
    
    public void setPrazoContrato(String prazoContrato) {
        this.prazoContrato = prazoContrato;
    }




}


