package model;
// Generated Oct 10, 2017 10:03:24 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente")
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nome;
  //   private String apelido;
     private String genero;
     private String nacionalidade;
     private String residencia;
     private String tipoDecumentoIdent;
     private String numero;
     private Date DataNascimento;
     private String contacto;
     private String contactoEmerg;
     private Date DataRegisto;
     

    public Cliente() {
    }

	
    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public Cliente(String nome, String genero, String nacionalidade, String residencia, String tipoDecumentoIdent, String numero, Date DataNascimento, String contacto, String contactoEmerg, Date DataRegisto) {
        this.nome = nome;
        this.genero = genero;
        this.nacionalidade = nacionalidade;
        this.residencia = residencia;
        this.tipoDecumentoIdent = tipoDecumentoIdent;
        this.numero = numero;
        this.DataNascimento = DataNascimento;
        this.contacto = contacto;
        this.contactoEmerg = contactoEmerg;
        this.DataRegisto = DataRegisto;
    }

  
  
   

   
   
   
     @Id 
@GeneratedValue
    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getDataNascimento() {
        return DataNascimento;
    }

    public void setDataNascimento(Date DataNascimento) {
        this.DataNascimento = DataNascimento;
    }

    public Date getDataRegisto() {
        return DataRegisto;
    }

    public void setDataRegisto(Date DataRegisto) {
        this.DataRegisto = DataRegisto;
    }

    
//    @Column(name="apelido", length=45)
//    public String getApelido() {
//        return this.apelido;
//    }
//    
//    public void setApelido(String apelido) {
//        this.apelido = apelido;
//    }

    
    @Column(name="genero", length=45)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="nacionalidade", length=45)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="residencia", length=45)
    public String getResidencia() {
        return this.residencia;
    }
    
    public void setResidencia(String residencia) {
        this.residencia = residencia;
    }

    
    @Column(name="tipoDecumentoIdent", length=45)
    public String getTipoDecumentoIdent() {
        return this.tipoDecumentoIdent;
    }
    
    public void setTipoDecumentoIdent(String tipoDecumentoIdent) {
        this.tipoDecumentoIdent = tipoDecumentoIdent;
    }

    public String getNumero() {
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    
  

//    @Temporal(TemporalType.DATE)
//    @Column(name="validade", length=10)
//    public Date getValidade() {
//        return this.validade;
//    }
//    
//    public void setValidade(Date validade) {
//        this.validade = validade;
//    }

    
    @Column(name="contacto", length=45)
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    
    @Column(name="contactoEmerg", length=45)
    public String getContactoEmerg() {
        return this.contactoEmerg;
    }
    
    public void setContactoEmerg(String contactoEmerg) {
        this.contactoEmerg = contactoEmerg;
    }






}


