package model;
// Generated Oct 10, 2017 10:03:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Residencia generated by hbm2java
 */
@Entity
@Table(name="residencia")
public class Residencia  implements java.io.Serializable {


     private int idResidencia;
     private String nome;
     private String bloco;
     private String  tipo;
     private String estado;
     private String  valorArendamento;
     private String  valorReabilitacaoMax;
     private String Localizacao;
     private String estadoOucupado;
     private Date dataRegisto;

    public Residencia() {
    }

	
    public Residencia(int idResidencia) {
        this.idResidencia = idResidencia;
    }

    public Residencia(int idResidencia, String nome, String bloco, String tipo, String estado, String valorArendamento, String valorReabilitacaoMax, String Localizacao, String estadoOucupado, Date dataRegisto) {
        this.idResidencia = idResidencia;
        this.nome = nome;
        this.bloco = bloco;
        this.tipo = tipo;
        this.estado = estado;
        this.valorArendamento = valorArendamento;
        this.valorReabilitacaoMax = valorReabilitacaoMax;
        this.Localizacao = Localizacao;
        this.estadoOucupado = estadoOucupado;
        this.dataRegisto = dataRegisto;
    }

    public Residencia(String nome, String bloco, String tipo, String estado, String valorArendamento, String valorReabilitacaoMax, String Localizacao, String estadoOucupado, Date dataRegisto) {
        this.nome = nome;
        this.bloco = bloco;
        this.tipo = tipo;
        this.estado = estado;
        this.valorArendamento = valorArendamento;
        this.valorReabilitacaoMax = valorReabilitacaoMax;
        this.Localizacao = Localizacao;
        this.estadoOucupado = estadoOucupado;
        this.dataRegisto = dataRegisto;
    }

   
     @Id 
@GeneratedValue
@Column(name="idResidencia", unique=true, nullable=false)
    public int getIdResidencia() {
        return this.idResidencia;
    }
    
    public void setIdResidencia(int idResidencia) {
        this.idResidencia = idResidencia;
    }

    
    @Column(name="bloco", length=45)
    public String getBloco() {
        return this.bloco;
    }
    
    public void setBloco(String bloco) {
        this.bloco = bloco;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getValorArendamento() {
        return valorArendamento;
    }

    public void setValorArendamento(String valorArendamento) {
        this.valorArendamento = valorArendamento;
    }

    public String getValorReabilitacaoMax() {
        return valorReabilitacaoMax;
    }

    public void setValorReabilitacaoMax(String valorReabilitacaoMax) {
        this.valorReabilitacaoMax = valorReabilitacaoMax;
    }

    public String getEstadoOucupado() {
        return estadoOucupado;
    }

    public void setEstadoOucupado(String estadoOucupado) {
        this.estadoOucupado = estadoOucupado;
    }

  public String getLocalizacao() {
        return Localizacao;
    }

    public void setLocalizacao(String Localizacao) {
        this.Localizacao = Localizacao;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="dataRegisto", length=10)
    public Date getDataRegisto() {
        return dataRegisto;
    }

    public void setDataRegisto(Date dataRegisto) {
        this.dataRegisto = dataRegisto;
    }

  


}


