/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import control.UsuariorDao;
import static java.awt.Frame.ICONIFIED;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.Utilizador;
import tabela.TabelaUsuario;

/**
 *
 * @author Armano
 */
public class Tela1Utilizador extends javax.swing.JInternalFrame {
 
    private static int id = 0;
    private Utilizador utilizador = new Utilizador();
    private List<Utilizador> list;
    private TabelaUsuario modelTable;
    UsuariorDao controle=new  UsuariorDao();
   // private TabelaUsuario modelTable = new TabelaUsuario();
    Utilizador Uti=new Utilizador();
    
    /** Creates new form Tela1Utilizador */
    public Tela1Utilizador() {
        initComponents();
        updateTable();
        limparCampos();
        jTabelaUsuario.setModel(modelTable);
        modelTable.lerTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserField1 = new javax.swing.JTextField();
        SenhaField2 = new javax.swing.JTextField();
        jCboCategoriaUsuario = new javax.swing.JComboBox<>();
        bontes1 = new javax.swing.JPanel();
        NovoUsuario = new javax.swing.JButton();
        DeletarUsuario = new javax.swing.JButton();
        RefreshUsuario = new javax.swing.JButton();
        SalvarUsuario = new javax.swing.JButton();
        PesaquisartField1 = new javax.swing.JTextField();
        PesquisaUsuario = new javax.swing.JButton();
        RelatorioUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaUsuario = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1052, 721));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Cadastrar Usuario");

        jLabel2.setText("User");

        jLabel3.setText("Senha");

        jLabel4.setText("Categoria");

        jCboCategoriaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCategoriaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(UserField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(SenhaField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addComponent(jCboCategoriaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(SenhaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCboCategoriaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        NovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addFunc32.png"))); // NOI18N
        NovoUsuario.setText("Novo");
        NovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoUsuarioActionPerformed(evt);
            }
        });

        DeletarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_3.png"))); // NOI18N
        DeletarUsuario.setText("Deletar");
        DeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarUsuarioActionPerformed(evt);
            }
        });

        RefreshUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-24.png"))); // NOI18N
        RefreshUsuario.setText("Actualizar");
        RefreshUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshUsuarioActionPerformed(evt);
            }
        });

        SalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Accept-icon32.png"))); // NOI18N
        SalvarUsuario.setText("Gravar");
        SalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarUsuarioActionPerformed(evt);
            }
        });

        PesquisaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pes32.jpg"))); // NOI18N

        RelatorioUsuario.setText("Relatorio");

        javax.swing.GroupLayout bontes1Layout = new javax.swing.GroupLayout(bontes1);
        bontes1.setLayout(bontes1Layout);
        bontes1Layout.setHorizontalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bontes1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(NovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(SalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RefreshUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(RelatorioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        bontes1Layout.setVerticalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bontes1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeletarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RefreshUsuario)
                        .addComponent(SalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RelatorioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(370, 370, 370))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bontes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bontes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboCategoriaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCategoriaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCategoriaUsuarioActionPerformed

    private void RefreshUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshUsuarioActionPerformed

    private void SalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarUsuarioActionPerformed
 try {
          
    
            String username = this.UserField1.getText();
            String password = this.SenhaField2.getText();

            String Categoria = this.jCboCategoriaUsuario.getSelectedItem() + "";

            Utilizador u = new Utilizador(ICONIFIED, Categoria, username, password, new Date());

            controle.salvar(u);
            modelTable.lerTabela();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Usuario gravado com sucesso");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de insersao : " + erro);
        }
    }//GEN-LAST:event_SalvarUsuarioActionPerformed

    private void NovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovoUsuarioActionPerformed

    private void DeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarUsuarioActionPerformed
        // TODO add your handling code here:
        
         try {

            TabelaUsuario tb = new TabelaUsuario(list);

            controle.removerUtilizador(id);
            modelTable.lerTabela();
//  
            //  controle.actualizar(funcionario);
            limparCampos();
               updateTable();
            JOptionPane.showMessageDialog(null, "Removido com sucesso!!!!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao remover" + ex);
        }
    }//GEN-LAST:event_DeletarUsuarioActionPerformed
 public void limparCampos() {

        UserField1.setText("");
        SenhaField2.setText("");
        jCboCategoriaUsuario.setSelectedIndex(-1);

    }
    private void jTabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaUsuarioMouseClicked
        // TODO add your handling code here:
        
        
      //  this.utilizador = modelTable.mouseclick(jTabelaUsuario.getSelectedRow());
        this.utilizador = this.list.get(jTabelaUsuario.getSelectedRow());
        id = utilizador.getIdutilizador();
        UserField1.setText(this.utilizador.getUsername());
        SenhaField2.setText(this.utilizador.getPassword());
        
        jCboCategoriaUsuario.setSelectedItem(this.utilizador.getCategoria());
        
    }//GEN-LAST:event_jTabelaUsuarioMouseClicked
public void updateTable(){
        this.list = controle.findAll();
        modelTable = new TabelaUsuario(list);
        jTabelaUsuario.setModel(modelTable);

       jTabelaUsuario.getColumnModel().getColumn(0).setPreferredWidth(300);
       jTabelaUsuario.getColumnModel().getColumn(0).setResizable(false);
       jTabelaUsuario.getColumnModel().getColumn(1).setPreferredWidth(150);
       jTabelaUsuario.getColumnModel().getColumn(1).setResizable(false);
       jTabelaUsuario.getColumnModel().getColumn(2).setPreferredWidth(150);
       jTabelaUsuario.getColumnModel().getColumn(2).setResizable(false);
       jTabelaUsuario.getColumnModel().getColumn(3).setPreferredWidth(200);
       jTabelaUsuario.getColumnModel().getColumn(3).setResizable(false);
       jTabelaUsuario.getColumnModel().getColumn(4).setPreferredWidth(200);
       jTabelaUsuario.getColumnModel().getColumn(4).setResizable(false);
       jTabelaUsuario.getTableHeader().setReorderingAllowed(false);
       jTabelaUsuario.setAutoResizeMode( jTabelaUsuario.AUTO_RESIZE_OFF);
       jTabelaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletarUsuario;
    private javax.swing.JButton NovoUsuario;
    private javax.swing.JTextField PesaquisartField1;
    private javax.swing.JButton PesquisaUsuario;
    private javax.swing.JButton RefreshUsuario;
    private javax.swing.JButton RelatorioUsuario;
    private javax.swing.JButton SalvarUsuario;
    private javax.swing.JTextField SenhaField2;
    private javax.swing.JTextField UserField1;
    private javax.swing.JPanel bontes1;
    private javax.swing.JComboBox<String> jCboCategoriaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaUsuario;
    // End of variables declaration//GEN-END:variables

}
