/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.FuncionarioDao;
import static java.awt.Frame.ICONIFIED;

import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import model.Funcionario;
import tabela.TabelaFuncionario;



/**
 *
 * @author Armano
 */
public class Tela1Fucionario extends javax.swing.JInternalFrame {
 private static int id = 0;
    private Funcionario funcionario = new Funcionario();
    private List<Funcionario> list;
    private TabelaFuncionario modelTable = new TabelaFuncionario();
    FuncionarioDao controle = new FuncionarioDao();

    /**
     * Creates new form Fucionario
     */
    public Tela1Fucionario() {
        initComponents();
         jTableFuncionario.setModel(modelTable);
        modelTable.lerTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeField1 = new javax.swing.JTextField();
        ApelidoField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NacionalidadeField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCboCategoria = new javax.swing.JComboBox<>();
        jRdoMasculino = new javax.swing.JRadioButton();
        jRdoFemenino = new javax.swing.JRadioButton();
        DataNacimentoField1 = new com.toedter.calendar.JDateChooser();
        bontes1 = new javax.swing.JPanel();
        jButNovoFuncionario = new javax.swing.JButton();
        jButDeletarFuncionario = new javax.swing.JButton();
        jButRefreshFuncionario = new javax.swing.JButton();
        jButSalvarFuncionario = new javax.swing.JButton();
        PesaquisartField1 = new javax.swing.JTextField();
        jButpesaquisaFuncionario = new javax.swing.JButton();
        jButRelatorioFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1052, 721));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Funcionarios");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel5.setText("Nacionalidade");

        jLabel6.setText("Genero");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Categoria");

        jCboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Gerente", "Operario", "" }));

        jRdoMasculino.setText("M");

        jRdoFemenino.setText("F");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApelidoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NacionalidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(jCboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DataNacimentoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jRdoMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jRdoFemenino)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(NacionalidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRdoMasculino)
                    .addComponent(jRdoFemenino))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ApelidoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jCboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(DataNacimentoField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addFunc32.png"))); // NOI18N
        jButNovoFuncionario.setText("NEW");
        jButNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNovoFuncionarioActionPerformed(evt);
            }
        });

        jButDeletarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_3.png"))); // NOI18N
        jButDeletarFuncionario.setText("Delete");
        jButDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDeletarFuncionarioActionPerformed(evt);
            }
        });

        jButRefreshFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-24.png"))); // NOI18N
        jButRefreshFuncionario.setText("Actualizar");
        jButRefreshFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRefreshFuncionarioActionPerformed(evt);
            }
        });

        jButSalvarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Accept-icon32.png"))); // NOI18N
        jButSalvarFuncionario.setText("Seve");
        jButSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalvarFuncionarioActionPerformed(evt);
            }
        });

        PesaquisartField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PesaquisartField1(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PesaquisartField11(evt);
            }
        });
        PesaquisartField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesaquisartField1ActionPerformed(evt);
            }
        });
        PesaquisartField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesaquisartField1KeyReleased(evt);
            }
        });

        jButpesaquisaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pes32.jpg"))); // NOI18N
        jButpesaquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButpesaquisaFuncionarioActionPerformed(evt);
            }
        });

        jButRelatorioFuncionario.setText("Relatorio");

        javax.swing.GroupLayout bontes1Layout = new javax.swing.GroupLayout(bontes1);
        bontes1.setLayout(bontes1Layout);
        bontes1Layout.setHorizontalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bontes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButRefreshFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButRelatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButpesaquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        bontes1Layout.setVerticalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bontes1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButpesaquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButRefreshFuncionario)
                        .addComponent(jButSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButRelatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionario(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(323, 323, 323)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(bontes1, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(bontes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        jButSalvarFuncionario.setEnabled(true);
        jButDeletarFuncionario.setEnabled(true);
        // jButNovoFuncionario.setEnabled(false);
        jButpesaquisaFuncionario.setEnabled(true);
        jButRefreshFuncionario.setEnabled(true);

        NomeField1.setEnabled(true);
        NacionalidadeField1.setEnabled(true);
        DataNacimentoField1.setEnabled(true);
        ApelidoField2.setEnabled(true);
        PesaquisartField1.setEnabled(true);
        jCboCategoria.setEnabled(true);
        jRdoFemenino.setEnabled(true);
        jRdoMasculino.setEnabled(true);

        limparCampos();
    }//GEN-LAST:event_jButNovoFuncionarioActionPerformed

    private void jButDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDeletarFuncionarioActionPerformed
        // TODO add your handling code here:

        try {

            TabelaFuncionario tb = new TabelaFuncionario(list);

            controle.removerFuncionario(id);
            modelTable.lerTabela();
            //
            //  controle.actualizar(funcionario);
            //   updateTable();
            JOptionPane.showMessageDialog(null, "Removido com sucesso!!!!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao remover" + ex);
        }
    }//GEN-LAST:event_jButDeletarFuncionarioActionPerformed

    private void jButRefreshFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRefreshFuncionarioActionPerformed
        // isFieldEmpty();
        //    desabilitar();//
        try {

            String genero = "Masculino";
            if (!jRdoMasculino.isSelected()) {
                genero = "Feminino";
            }
            String nome = this.NomeField1.getText();
            String apelido = this.ApelidoField2.getText();
            String nacionalidade = this.NacionalidadeField1.getText();
            //  String idFuncionario = this.IDtField1.getText();
            Date datanascimento = this.DataNacimentoField1.getDate();
            String categoria = this.jCboCategoria.getSelectedItem() + "";

            Funcionario funcionario = new Funcionario(ICONIFIED, nome, apelido, nacionalidade, genero, categoria, datanascimento, new Date());

            controle.actualizar(id, funcionario);

//            desabilitar();
            JOptionPane.showMessageDialog(null, "Funcionario salvo com sucesso");

            // desabilitar();
            limparCampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro de insersao : " + erro);
        }
        modelTable.lerTabela();
        //updateTable();
    }//GEN-LAST:event_jButRefreshFuncionarioActionPerformed

    private void jButSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalvarFuncionarioActionPerformed
        // TODO add your handling codle here:
        //isFieldEmpty();

        try {

            String genero = "Masculino";
            if (!jRdoMasculino.isSelected()) {
                genero = "Masculino";
            }

            if (!jRdoFemenino.isSelected()) {
                genero = "Feminino";}
            //          // idFuncionario = this.IDtField1);
        String nome = this.NomeField1.getText();
        String apelido = this.ApelidoField2.getText();
        String nacionalidade = this.NacionalidadeField1.getText();
        Date datanascimento = this.DataNacimentoField1.getDate();
        String categoria = this.jCboCategoria.getSelectedItem() + "";
        Funcionario funcionario = new Funcionario(ICONIFIED, nome, apelido, nacionalidade, genero, categoria, datanascimento, new Date());

        controle.salvar(funcionario);
       // updateTable();
        //  desabilitar();
        JOptionPane.showMessageDialog(null, "Funcionario salvo com sucesso");

      //  limparCampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro de insersao : " + erro);
        }
        modelTable.lerTabela();
    }//GEN-LAST:event_jButSalvarFuncionarioActionPerformed

    private void PesaquisartField1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PesaquisartField1
        // TODO add your handling code here:

    }//GEN-LAST:event_PesaquisartField1

    private void PesaquisartField11(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PesaquisartField11
        // TODO add your handling code here:

    }//GEN-LAST:event_PesaquisartField11

    private void PesaquisartField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesaquisartField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PesaquisartField1ActionPerformed

    private void PesaquisartField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesaquisartField1KeyReleased
        // TODO add your handling code here:
        modelTable.lerTabela(PesaquisartField1.getText());

    }//GEN-LAST:event_PesaquisartField1KeyReleased

    private void jButpesaquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButpesaquisaFuncionarioActionPerformed

        //
    }//GEN-LAST:event_jButpesaquisaFuncionarioActionPerformed

    private void jTableFuncionario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionario
        // TODO add your handling code here:
        //        fillFields();
        //      //jButSalvarFuncionario.setEnabled(true);
        jButDeletarFuncionario.setEnabled(true);
        //        jButNovoFuncionario.setEnabled(false);
        //        jButpesaquisaFuncionario.setEnabled(true);
        jButRefreshFuncionario.setEnabled(true);
        //

        this.funcionario = modelTable.mouseclick(jTableFuncionario.getSelectedRow());
        id = funcionario.getIdfuncionario();
        NomeField1.setText(this.funcionario.getNome());
        NacionalidadeField1.setText(this.funcionario.getNacionalidade());
        DataNacimentoField1.setDate(this.funcionario.getDataNascimento());
        ApelidoField2.setText(this.funcionario.getApelido());
        jCboCategoria.setSelectedItem(this.funcionario.getCategoria());

    }//GEN-LAST:event_jTableFuncionario

     public void desabilitar() {
        jButSalvarFuncionario.setEnabled(false);
        jButDeletarFuncionario.setEnabled(false);
        // jButNovoFuncionario.setEnabled(false);
        jButpesaquisaFuncionario.setEnabled(false);
        jButRefreshFuncionario.setEnabled(false);

        jCboCategoria.setEnabled(false);
        NomeField1.setEnabled(false);
        NacionalidadeField1.setEnabled(false);
        DataNacimentoField1.setEnabled(false);
        ApelidoField2.setEnabled(false);
//        jRdoFemenino.setEnabled(false);
//        jRdoMasculino.setEnabled(false);
        PesaquisartField1.setEnabled(false);

        limparCampos();
    }

    //Metodo para limpar os campos
    public void limparCampos() {

        NomeField1.setText("");
        NacionalidadeField1.setText("");
        //   DataNacimentoField1.setDate();
        ApelidoField2.setText("");

        jRdoFemenino.setEnabled(false);
        jRdoMasculino.setEnabled(false);
        jCboCategoria.setSelectedIndex(-1);

    }

//    public void Validacoes() {
//        validarNome();
//        validarApelido();
//        validarNacionalidade();
//
//    }

//    public boolean validarNome() {
//        if (NomeField1.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "somente texto");
//            return false;
//        }
//        return false;
//    }
//
//    public boolean validarApelido() {
//        if (ApelidoField2.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "somente texto");
//            return false;
//        }
//        return false;
//    }
//
//    public boolean validarNacionalidade() {
//        if (NacionalidadeField1.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "somente texto");
//            return false;
//        }
//        return false;
//    }


    private void fillFields() {

        this.funcionario = this.list.get(jTableFuncionario.getSelectedRow());
        id = funcionario.getIdfuncionario();
        NomeField1.setText(this.funcionario.getNome());
        NacionalidadeField1.setText(this.funcionario.getNacionalidade());
        DataNacimentoField1.setDate(this.funcionario.getDataNascimento());
        ApelidoField2.setText(this.funcionario.getApelido());
//       .setAction(this.funcionario.getCategoria());
        // jCboCategoria.getItemAt(this.funcionario.setCategoria());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApelidoField2;
    private com.toedter.calendar.JDateChooser DataNacimentoField1;
    private javax.swing.JTextField NacionalidadeField1;
    private javax.swing.JTextField NomeField1;
    private javax.swing.JTextField PesaquisartField1;
    private javax.swing.JPanel bontes1;
    private javax.swing.JButton jButDeletarFuncionario;
    private javax.swing.JButton jButNovoFuncionario;
    private javax.swing.JButton jButRefreshFuncionario;
    private javax.swing.JButton jButRelatorioFuncionario;
    private javax.swing.JButton jButSalvarFuncionario;
    private javax.swing.JButton jButpesaquisaFuncionario;
    private javax.swing.JComboBox<String> jCboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdoFemenino;
    private javax.swing.JRadioButton jRdoMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    // End of variables declaration//GEN-END:variables
}
