/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tabela.TabelaFuncionario;
import control.FuncionarioDao;
import java.util.Date;
import java.util.List;
import javafx.scene.chart.PieChart.Data;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import model.Funcionario;


/**
 *
 * @author Armano
 */
public class TelaFuncionario extends javax.swing.JFrame {
   
    
    private Funcionario funcionario;
    private List<Funcionario> list;
    private TabelaFuncionario modelTable;
    FuncionarioDao controle = new FuncionarioDao();
    
    
    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
      //  desabilitar();
        updateTable();
        isFieldEmpty();
        // Validacoes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bontes1 = new javax.swing.JPanel();
        jButNovoFuncionario = new javax.swing.JButton();
        jButDeletarFuncionario = new javax.swing.JButton();
        jButRefreshFuncionario = new javax.swing.JButton();
        jButSalvarFuncionario = new javax.swing.JButton();
        PesaquisartField1 = new javax.swing.JTextField();
        jButpesaquisaFuncionario = new javax.swing.JButton();
        jButRelatorioFuncionario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeField1 = new javax.swing.JTextField();
        ApelidoField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NacionalidadeField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DataNacimentoField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCboCategoria = new javax.swing.JComboBox<>();
        jRdoMasculino = new javax.swing.JRadioButton();
        jRdoFemenino = new javax.swing.JRadioButton();
        IDtField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));

        jButNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addFunc32.png"))); // NOI18N
        jButNovoFuncionario.setText("NEW");
        jButNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNovoFuncionarioActionPerformed(evt);
            }
        });

        jButDeletarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete_3.png"))); // NOI18N
        jButDeletarFuncionario.setText("Delete");
        jButDeletarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDeletarFuncionarioActionPerformed(evt);
            }
        });

        jButRefreshFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-24.png"))); // NOI18N
        jButRefreshFuncionario.setText("Actualizar");
        jButRefreshFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRefreshFuncionarioActionPerformed(evt);
            }
        });

        jButSalvarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Accept-icon32.png"))); // NOI18N
        jButSalvarFuncionario.setText("Save");
        jButSalvarFuncionario.setActionCommand("Save");
        jButSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalvarFuncionarioActionPerformed(evt);
            }
        });

        PesaquisartField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PesaquisartField1(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PesaquisartField1(evt);
            }
        });

        jButpesaquisaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pes32.jpg"))); // NOI18N

        jButRelatorioFuncionario.setText("Relatorio");

        javax.swing.GroupLayout bontes1Layout = new javax.swing.GroupLayout(bontes1);
        bontes1.setLayout(bontes1Layout);
        bontes1Layout.setHorizontalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bontes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButRefreshFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButRelatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButpesaquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        bontes1Layout.setVerticalGroup(
            bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bontes1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButpesaquisaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bontes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButNovoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButDeletarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButRefreshFuncionario)
                        .addComponent(jButSalvarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PesaquisartField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButRelatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel5.setText("Nacionalidade");

        jLabel6.setText("Genero");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Categoria");

        jCboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Gerente", "Operario", "" }));

        jRdoMasculino.setText("M");

        jRdoFemenino.setText("F");

        jLabel4.setText("ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ApelidoField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NacionalidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(jCboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataNacimentoField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IDtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jRdoMasculino)
                        .addGap(18, 18, 18)
                        .addComponent(jRdoFemenino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(NacionalidadeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jRdoMasculino)
                    .addComponent(jRdoFemenino)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ApelidoField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(DataNacimentoField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionario(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionario);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Funcionarios");

        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(bontes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bontes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void updateTable(){
        this.list = controle.findAll();
        modelTable = new TabelaFuncionario(list);
        jTableFuncionario.setModel(modelTable);

        jTableFuncionario.getColumnModel().getColumn(0).setPreferredWidth(300);
        jTableFuncionario.getColumnModel().getColumn(0).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableFuncionario.getColumnModel().getColumn(1).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableFuncionario.getColumnModel().getColumn(2).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableFuncionario.getColumnModel().getColumn(3).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTableFuncionario.getColumnModel().getColumn(4).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTableFuncionario.getColumnModel().getColumn(5).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTableFuncionario.getColumnModel().getColumn(6).setResizable(false);
        jTableFuncionario.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTableFuncionario.getColumnModel().getColumn(7).setResizable(false);
        
        jTableFuncionario.getTableHeader().setReorderingAllowed(false);
        
        jTableFuncionario.setAutoResizeMode(jTableFuncionario.AUTO_RESIZE_OFF);
        jTableFuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    private void jButNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        jButSalvarFuncionario.setEnabled(true);
        jButDeletarFuncionario.setEnabled(true);
       // jButNovoFuncionario.setEnabled(false);
        jButpesaquisaFuncionario.setEnabled(true);
        jButRefreshFuncionario.setEnabled(true);
        
        NomeField1.setEnabled(true);
        NacionalidadeField1.setEnabled(true);
        DataNacimentoField1.setEnabled(true);
        ApelidoField2.setEnabled(true);
        PesaquisartField1.setEnabled(true);
        jCboCategoria.setEnabled(true);
        jRdoFemenino.setEnabled(true);
        jRdoMasculino.setEnabled(true);
        
        limparCampos();
    }//GEN-LAST:event_jButNovoFuncionarioActionPerformed
/**
     * Metodo chamado para verificar se existe algum textfield sem nenhum input
     *
     * @return
     */
    
    private boolean isFieldEmpty() {

        if (NomeField1.getText().equalsIgnoreCase("")) {
            NomeField1.requestFocus();
            return true;
        }
        if (NacionalidadeField1.getText().equalsIgnoreCase("")) {
            NacionalidadeField1.requestFocus();
            return true;
        }
        if (jCboCategoria.getSelectedItem() == null) {
            jCboCategoria.requestFocus();
            return true;
        }
        if (DataNacimentoField1.getText().equalsIgnoreCase("")) {
           DataNacimentoField1.requestFocus();
            return true;
        }
    if (ApelidoField2.getText().equalsIgnoreCase("")) {
          ApelidoField2.requestFocus();
            return true;
        }
     if (jRdoFemenino.getText().equalsIgnoreCase("")) {
           jRdoFemenino.requestFocus();
            return true;
        }


        return false;

    }
    private void jButSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalvarFuncionarioActionPerformed
        // TODO add your handling codle here:
        isFieldEmpty();
       
        try {
          
            String genero = "Masculino";
            if (!jRdoMasculino.isSelected()) {
            genero = "Masculino";
            }
             
             if (!jRdoFemenino.isSelected()) {
            genero = "Feminino";}
          // idFuncionario = this.IDtField1);
            String nome = this.NomeField1.getText();
            String apelido = this.ApelidoField2.getText();
            String nacionalidade = this.NacionalidadeField1.getText();
            String datanascimento = this.DataNacimentoField1.getText();
            String categoria = this.jCboCategoria.getSelectedItem() + "";
            Funcionario funcionario = new Funcionario(ICONIFIED, nome, apelido, nacionalidade, genero, categoria, datanascimento,new  Date());

            controle.salvar(funcionario);
            updateTable();
            desabilitar();
            JOptionPane.showMessageDialog(null, "Funcionario salvo com sucesso");
            
            limparCampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro de insersao : " + erro);
        }
    }//GEN-LAST:event_jButSalvarFuncionarioActionPerformed

    private void PesaquisartField1(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PesaquisartField1
        // TODO add your handling code here:
        PesaquisartField1.setText("Pesquisar");
    }//GEN-LAST:event_PesaquisartField1

    private void jButRefreshFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRefreshFuncionarioActionPerformed
     // isFieldEmpty();
    //    desabilitar();//
        try {
            
            String genero = "Masculino";
            if (!jRdoMasculino.isSelected()) {
                genero = "Feminino";
            }
            String nome = this.NomeField1.getText();
            String apelido = this.ApelidoField2.getText();
            String nacionalidade = this.NacionalidadeField1.getText();
          //  String idFuncionario = this.IDtField1.getText();
            String datanascimento = this.DataNacimentoField1.getText();
            String categoria = this.jCboCategoria.getSelectedItem() + "";

            Funcionario funcionario = new Funcionario(ICONIFIED, nome, apelido, nacionalidade, genero, categoria, datanascimento,new  Date());

            controle.actualizar(funcionario);
            updateTable();
            desabilitar();
            JOptionPane.showMessageDialog(null, "Funcionario salvo com sucesso");

            desabilitar();
            limparCampos();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "erro de insersao : " + erro);
        }
        
    }//GEN-LAST:event_jButRefreshFuncionarioActionPerformed

    private void jButDeletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDeletarFuncionarioActionPerformed
        // TODO add your handling code here:

        try {

            TabelaFuncionario tb = new TabelaFuncionario(list);

            controle.removerFuncionario((int) jTableFuncionario.getValueAt(jTableFuncionario.getSelectedRow(), 0));

//  
            //  controle.actualizar(funcionario);
            updateTable();
            JOptionPane.showMessageDialog(null, "Removido com sucesso!!!!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao remover" + ex);
        }
    }//GEN-LAST:event_jButDeletarFuncionarioActionPerformed

    private void jTableFuncionario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionario
        // TODO add your handling code here:
        fillFields();
      //jButSalvarFuncionario.setEnabled(true);
        jButDeletarFuncionario.setEnabled(true);
      //jButNovoFuncionario.setEnabled(false);
        jButpesaquisaFuncionario.setEnabled(true);
        jButRefreshFuncionario.setEnabled(true);
        
        NomeField1.setEnabled(true);
        NacionalidadeField1.setEnabled(true);
        DataNacimentoField1.setEnabled(true);
        ApelidoField2.setEnabled(true);
        PesaquisartField1.setEnabled(true);
        jCboCategoria.setEnabled(true);
        jRdoFemenino.setEnabled(true);
        jRdoMasculino.setEnabled(true);
    }//GEN-LAST:event_jTableFuncionario

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApelidoField2;
    private javax.swing.JTextField DataNacimentoField1;
    private javax.swing.JTextField IDtField1;
    private javax.swing.JTextField NacionalidadeField1;
    private javax.swing.JTextField NomeField1;
    private javax.swing.JTextField PesaquisartField1;
    private javax.swing.JPanel bontes1;
    private javax.swing.JButton jButDeletarFuncionario;
    private javax.swing.JButton jButNovoFuncionario;
    private javax.swing.JButton jButRefreshFuncionario;
    private javax.swing.JButton jButRelatorioFuncionario;
    private javax.swing.JButton jButSalvarFuncionario;
    private javax.swing.JButton jButpesaquisaFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdoFemenino;
    private javax.swing.JRadioButton jRdoMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    // End of variables declaration//GEN-END:variables

 public void desabilitar(){
        jButSalvarFuncionario.setEnabled(false);
        jButDeletarFuncionario.setEnabled(false);
       // jButNovoFuncionario.setEnabled(false);
        jButpesaquisaFuncionario.setEnabled(false);
        jButRefreshFuncionario.setEnabled(false);
        
        jCboCategoria.setEnabled(false);
        NomeField1.setEnabled(false);
        NacionalidadeField1.setEnabled(false);
        DataNacimentoField1.setEnabled(false);
        ApelidoField2.setEnabled(false);
//        jRdoFemenino.setEnabled(false);
//        jRdoMasculino.setEnabled(false);
        PesaquisartField1.setEnabled(false);
     
        limparCampos();
    }
    
    //Metodo para limpar os campos
    public void limparCampos(){

        NomeField1.setText("");
        NacionalidadeField1.setText("");
        DataNacimentoField1.setText("");
        ApelidoField2.setText("");
        
        jRdoFemenino.setEnabled(false);
        jRdoMasculino.setEnabled(false);
        jCboCategoria.setSelectedIndex(-1);
        
    }
        public void Validacoes (){
            validarNome();
        validarApelido();
        validarNacionalidade();
        
        }
    
      public boolean validarNome(){
       if (NomeField1.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "somente texto");
           return false;
       }
       return false;
   }  public boolean validarApelido(){
       if (ApelidoField2.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "somente texto");
           return false;
       }
       return false;
   }  public boolean validarNacionalidade(){
       if ( NacionalidadeField1.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "somente texto");
           return false;
       }
       return false;
   }
//   }  public boolean validarCampos(){
//       if (NomeField1.getText().isEmpty()) {
//           JOptionPane.showMessageDialog(null, "Informe o nome");
//           return false;
//       }
//       return false;
//   }
      private void fillFields(){
          
        this.funcionario=this.list.get(jTableFuncionario.getSelectedRow());
       
        NomeField1.setText(this.funcionario.getNome());
        NacionalidadeField1.setText(this.funcionario.getNacionalidade());
        DataNacimentoField1.setText(this.funcionario.getDataNascimento());
        ApelidoField2.setText(this.funcionario.getApelido());
//       .setAction(this.funcionario.getCategoria());
          // jCboCategoria.getItemAt(this.funcionario.setCategoria());
    }
}
