package model;
// Generated Oct 10, 2017 10:03:24 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="cedascasas"
)
public class Funcionario  implements java.io.Serializable {


     private int idfuncionario;
     private String nome;
     private String apelido;
     private String nacionalidade;
     private String genero;
     private String funcao;
     private String categoria;
     private Date dataRegisto;
     

    public Funcionario() {
    }

	
    public Funcionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public Funcionario(int idfuncionario, String nome, String apelido, String nacionalidade, String genero, String funcao, String categoria, Date dataRegisto) {
       this.idfuncionario = idfuncionario;
       this.nome = nome;
       this.apelido = apelido;
       this.nacionalidade = nacionalidade;
       this.genero = genero;
       this.funcao = funcao;
       this.categoria = categoria;
       this.dataRegisto = dataRegisto;
      
    }
   
     @Id 

    
    @Column(name="idfuncionario", unique=true, nullable=false)
    public int getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(int idfuncionario) {
        this.idfuncionario = idfuncionario;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="apelido", length=45)
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    
    @Column(name="nacionalidade", length=45)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="genero", length=45)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="funcao", length=45)
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }

    
    @Column(name="categoria", length=45)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataRegisto", length=10)
    public Date getDataRegisto() {
        return this.dataRegisto;
    }
    
    public void setDataRegisto(Date dataRegisto) {
        this.dataRegisto = dataRegisto;
    }


    }







